import BodySection2 from "../landing/BodySection2";
import Navbar from "../landing/Navbar";
import "./About.css";

function About() {
  return (
    <div>
      <Navbar />
      <div>
        <div className="top-credit">
          <div className="about-title">
            <span>About</span>the project
          </div>
          <div className="about-top-content">
            <div>
              <div className="sp-bold">
                <span>Clinical access</span> to relevant key-frames from an
                ultrasound scan video.
              </div>
              <ul>
                <br />
                <br />
                <li>
                Ultrasound lung videos are uploaded using an obliquely positioned probe.
                Uploads occur via a POST web request from a front-end interface.
                FastAPI on a Uvicorn server manages responses based on client-side requests.
                </li>
                <br />
                <li>
                A unique identifier key is generated by the backend server upon video upload.
                This key facilitates future client-server communication.
                </li>
                <br />
                <li>
                Large uploaded videos are summarised to identify pathologically important frames.
                An ensemble encoder-LSTM decoder model is used for unsupervised video summarisation.
                Summarisation enhances utility in emergency departments and telemedicine.
                </li>
                <br />
                <li>
                An AI-driven object detection model with active learning identifies important landmarks in lung videos.
                Object tagging is performed using the YOLOv5 algorithm, treating summarised videos as a multi-class problem.
                </li>
                <br />
                <li>
                Segmentation of key landmarks and classification of lung video frames (normal vs. abnormal) aids in clinical decision-making.
                Valuable in limited-resource clinical settings and during pandemics.
                </li>
                <br />
                <li>
                URLs for summarised videos and keyframes are transmitted back to the front end.
                Display of summarised videos and random keyframes on the front end based on user preference.
                </li>
                <br />
                <li>
                A-lines are considered a normal finding in lung ultrasound and are indicative of air-filled lung tissue without significant abnormalities such as consolidation or effusion.
                </li>
             
              <br />
                <li>
                The presence of B-lines can indicate various pathological conditions affecting the lungs, such as pulmonary edema, interstitial lung disease, or pneumonia. The number, distribution, and characteristics of B-lines can aid in differentiating between different lung pathologies.
                </li>
                <br />
                <li>
                The visualization of a normal pleural line with lung sliding indicates healthy lung function and proper ventilation of the lungs. It reflects the normal interaction between the lungs and the chest wall during breathing.
                </li>
                </ul>
                

            </div>
            <div className="side-img-container">
              <img className="sir" src="./Group71.png" alt="photo" />
              {/* <img className="overlap-img" src="./Group71.png" alt="photo" /> */}
              <iframe
                className="overlap-img"
                // width="942"
                height="300"
            
                title="Web5... The Web3 Killer?"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen
              ></iframe>
            </div>
          </div>
        </div>
        <div className="hb-container">
          <div>
            An automated clinically scoring and reporting lung ultrasound tool
            for real-time analysis of lung ultrasound videos.
          </div>
        </div>
        <div className="sp-container">
          <img className="sp-img" src="./sp-img.png" alt="photo" />
          <div className="sp-content">
            14 lung videos obtained using the obliquely positioned probe along
            the posterior, anterior, and lateral chest walls.
          </div>
        </div>
        <div className="git-link">
         
        </div>
        <BodySection2 />
      </div>
    </div>
  );
}

export default About;
